# SUBIR O CONTAINER: docker compose up -d 
# PARAR O CONTAINER: docker compose stop
# MATAR O CONTAINER: docker compose down

version: '3'

services:
  postgres-docker:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=apisolid